#include "../include/omni_serve.h"

#include <iostream>
#include <vector>
#include <numeric>
#include <cmath>
#include <algorithm>

// Conceptual XLA Custom Call Header (Based on standard TensorFlow/XLA Bazel toolchain)
// This registry allows the compiled StableHLO binary to resolve C++ function pointers by string name.
#include "xla/ffi/ffi.h"
#include "xla/service/custom_call_target_registry.h"

// ==============================================================================
// OMNI-ATTENTION: OMNI-SERVE INFERENCE RUNTIME (XLA CUSTOM CALLS)
// Project Phase 4: Production C++ Serving Infrastructure
// Architecture Targets: CPU Host fallback for irregular control-flow logic
// ==============================================================================

namespace omni_serve {
namespace CustomOps {

// ------------------------------------------------------------------------------
// 1. Specialized Token Sampling (Top-P / Nucleus Sampling)
// ------------------------------------------------------------------------------
/**
 * Expected XLA FFI (Foreign Function Interface) Signature.
 * * @param out Pointer to the output buffer (will store the 1x int32 chosen token).
 * @param in  Array of pointers to the input buffers provided by the XLA graph.
 * in[0]: float* -> The raw logits array [vocab_size]
 * in[1]: float* -> The Top-P threshold scalar (e.g., 0.9)
 * in[2]: float* -> A random uniform value [0.0, 1.0) generated by the device PRNG
 * in[3]: int32* -> The vocabulary size scalar
 */
extern "C" void CustomTopP(void* out, void** in) {
    // 1. Parse raw memory pointers back into usable C++ types
    const float* logits = static_cast<const float*>(in[0]);
    const float top_p = *static_cast<const float*>(in[1]);
    const float random_val = *static_cast<const float*>(in[2]);
    const int32_t vocab_size = *static_cast<const int32_t*>(in[3]);

    int32_t* output_token_id = static_cast<int32_t*>(out);

    // 2. Compute Softmax (Convert logits to probabilities)
    std::vector<float> probs(vocab_size);
    float max_logit = -std::numeric_limits<float>::infinity();
    for (int i = 0; i < vocab_size; ++i) {
        if (logits[i] > max_logit) {
            max_logit = logits[i];
        }
    }

    float sum_exp = 0.0f;
    for (int i = 0; i < vocab_size; ++i) {
        probs[i] = std::exp(logits[i] - max_logit);
        sum_exp += probs[i];
    }
    
    for (int i = 0; i < vocab_size; ++i) {
        probs[i] /= sum_exp;
    }

    // 3. Prepare for sorting (We need to remember original token indices)
    std::vector<std::pair<float, int32_t>> prob_indices(vocab_size);
    for (int32_t i = 0; i < vocab_size; ++i) {
        prob_indices[i] = {probs[i], i};
    }

    // Sort descending by probability
    std::sort(prob_indices.begin(), prob_indices.end(), 
              [](const std::pair<float, int32_t>& a, const std::pair<float, int32_t>& b) {
                  return a.first > b.first;
              });

    // 4. Nucleus (Top-P) Filtering
    float cumulative_prob = 0.0f;
    int32_t cutoff_index = 0;
    
    for (int32_t i = 0; i < vocab_size; ++i) {
        cumulative_prob += prob_indices[i].first;
        cutoff_index = i;
        if (cumulative_prob >= top_p) {
            break; // We have isolated the probability "nucleus"
        }
    }

    // 5. Sample from the Nucleus using the provided random_val
    // We scale the random value by the cumulative probability of our cutoff slice
    // to represent a re-normalized probability distribution.
    float target_prob = random_val * cumulative_prob;
    float current_sum = 0.0f;
    
    for (int32_t i = 0; i <= cutoff_index; ++i) {
        current_sum += prob_indices[i].first;
        if (current_sum >= target_prob) {
            *output_token_id = prob_indices[i].second;
            return;
        }
    }

    // Fallback (Precision drift safety)
    *output_token_id = prob_indices[cutoff_index].second;
}

// ------------------------------------------------------------------------------
// 2. XLA Registry Hook
// ------------------------------------------------------------------------------
void RegisterCustomCalls() {
    std::cout << "[Omni-Serve] Registering XLA Custom Call: 'CustomTopP'" << std::endl;
    
    // Binds the string identifier "CustomTopP" (which JAX/Pallas will emit in the HLO)
    // to our compiled C++ function pointer in memory.
    xla::CustomCallTargetRegistry::Global()->Register(
        "CustomTopP", 
        reinterpret_cast<void*>(CustomTopP), 
        "Host" // Specifically registering this to execute on the CPU Host
    );
}

} // namespace CustomOps
} // namespace omni_serve